"""Food static data and JSON fallback loaders."""

from __future__ import annotations

from modules.food_utils import _load_json


_AREA_REGIONS = {
    "北部":   ["台北", "新北", "基隆", "桃園", "新竹", "苗栗"],
    "中部":   ["台中", "彰化", "南投", "雲林"],
    "南部":   ["嘉義", "台南", "高雄", "屏東"],
    "東部離島": ["宜蘭", "花蓮", "台東", "澎湖", "金門", "連江"],
}
_ALL_CITIES = [c for cities in _AREA_REGIONS.values() for c in cities]

# ── 氣象署城市對照表 ──
_CWA_CITY_MAP = {
    "台北": "臺北市", "台中": "臺中市", "台南": "臺南市", "高雄": "高雄市",
    "新北": "新北市", "桃園": "桃園市", "基隆": "基隆市",
    "新竹": "新竹縣", "苗栗": "苗栗縣", "彰化": "彰化縣",
    "南投": "南投縣", "雲林": "雲林縣", "嘉義": "嘉義縣",
    "屏東": "屏東縣", "宜蘭": "宜蘭縣", "花蓮": "花蓮縣",
    "台東": "臺東縣", "澎湖": "澎湖縣", "金門": "金門縣", "連江": "連江縣",
}

# ─── 今天吃什麼 ──────────────────────────────────────

# ── 食物關鍵字分類（入口觸發 + 分類解析共用）──
_STYLE_KEYWORDS: dict = _load_json("style_keywords.json", {})
if not _STYLE_KEYWORDS:
    _STYLE_KEYWORDS = {
    "便當": ["便當", "排骨", "雞腿", "控肉", "滷肉飯", "自助餐",
             "燒臘", "豬腳", "雞肉飯", "焢肉", "魯肉飯", "飯", "燒肉飯", "咖哩飯"],
    "麵食": ["麵", "拉麵", "牛肉麵", "乾麵", "河粉", "義大利",
             "鍋燒", "涼麵", "麵線", "切仔", "米粉", "粄條", "刀削", "餛飩", "炒麵",
             "擔仔麵", "陽春麵", "酸辣"],
    "小吃": ["小吃", "蚵仔", "臭豆腐", "肉圓", "鹽酥雞", "雞排", "滷味", "水餃", "鍋貼",
             "鹹水雞", "潤餅", "蔥油餅", "蔥抓餅", "大腸包小腸", "豬血糕", "碗粿",
             "米糕", "筒仔米糕", "麻糬", "地瓜球", "春捲", "炸物", "香腸",
             "關東煮", "雞蛋糕", "車輪餅", "紅豆餅", "章魚燒"],
    "火鍋": ["火鍋", "麻辣", "薑母鴨", "羊肉爐", "豆腐鍋",
             "涮涮鍋", "鍋物", "石頭鍋", "酸菜白肉", "牛奶鍋", "藥膳", "螃蟹鍋",
             "壽喜燒", "泡菜鍋", "麻油雞"],
    "日韓": ["日式", "日韓", "壽司", "丼飯", "韓式", "燒肉", "居酒屋", "咖哩",
             "生魚片", "定食", "韓式炸雞", "拌飯", "炸豬排", "天婦羅",
             "烏龍", "味噌", "鰻魚", "炸蝦", "石鍋", "部隊鍋", "年糕"],
    "早午餐": ["早午餐", "早餐", "蛋餅", "飯糰", "燒餅", "吐司", "三明治",
               "豆漿", "蘿蔔糕", "粥", "漢堡", "鬆餅", "可頌", "brunch",
               "法式吐司", "班尼迪克蛋", "歐姆蛋"],
    "飲料甜點": ["飲料", "甜點", "珍奶", "珍珠", "蛋糕", "咖啡", "豆花", "冰", "果汁", "奶茶",
                 "仙草", "愛玉", "抹茶", "冰淇淋", "芋圓", "手搖", "茶", "可可",
                 "鬆餅", "銅鑼燒", "甜湯", "紅豆湯", "花生湯", "湯圓"],
    "輕食": ["輕食", "沙拉", "健康", "低卡", "減脂", "清爽", "優格", "燕麥",
             "水煮餐", "無糖", "蛋白質", "健身餐", "貝果"],
    "台式早餐": ["台式早餐", "蛋餅", "飯糰", "燒餅", "豆漿", "蘿蔔糕", "鹹豆漿"],
    "西式早餐": ["西式早餐", "班尼迪克蛋", "法式吐司", "歐姆蛋", "美式早餐"],
    "燒烤": ["燒烤", "烤肉", "串燒", "炭烤", "烤雞", "BBQ", "烤串"],
    "港式": ["港式", "飲茶", "港點", "粵式", "叉燒", "燒鴨", "蝦餃"],
    "義式": ["義式", "披薩", "pasta", "燉飯", "焗烤", "義大利麵"],
    "素食": ["素食", "蔬食", "全素", "純素", "齋", "素料"],
    "粥": ["粥", "廣式粥", "皮蛋瘦肉粥", "稀飯", "鹹粥"],
    "麵包蛋糕": ["麵包", "烘焙", "貝果", "可頌", "甜甜圈", "蛋糕店", "烘焙坊"],
    "夜市小吃": ["夜市", "夜市小吃", "鹽酥雞", "大腸包小腸", "臭豆腐", "關東煮"],
    "炸物": ["炸物", "鹽酥雞", "炸雞排", "炸雞", "雞排", "炸物攤"],
    "拉麵": ["拉麵", "日式拉麵", "豚骨", "沾麵", "拉麵店"],
}  # fallback
# 扁平化所有食物關鍵字（供入口觸發用）
# 排除太通用的短詞，避免誤觸（這些詞仍用於分類解析）
_FOOD_TRIGGER_SKIP = {"麵", "飯", "冰", "茶", "粥", "健康", "早餐", "清爽"}
_ALL_FOOD_KEYWORDS: set = set()
for _kws in _STYLE_KEYWORDS.values():
    _ALL_FOOD_KEYWORDS.update(w for w in _kws if w not in _FOOD_TRIGGER_SKIP)

_FOOD_DB: dict = _load_json("food_db.json", {})
if not _FOOD_DB:
    # m: "M"=早餐限定  "D"=午餐以後  "N"=晚餐消夜限定  ""=全天
    _FOOD_DB = {
    "便當": [
        {"name": "排骨便當", "desc": "炸得香脆大排骨，台式便當之王", "price": "~100–140元", "key": "排骨便當", "m": "D"},
        {"name": "雞腿便當", "desc": "滷雞腿或炸雞腿，便當店人氣王", "price": "~100–140元", "key": "雞腿便當", "m": "D"},
        {"name": "控肉飯", "desc": "油亮滷汁入口即化，淋白飯上超滿足", "price": "~80–130元", "key": "控肉飯", "m": "D"},
        {"name": "焢肉飯", "desc": "厚切五花肉滷到透亮，經典台式", "price": "~80–120元", "key": "焢肉飯", "m": "D"},
        {"name": "燒臘雙拼飯", "desc": "港式叉燒鴨配油飯，大份量", "price": "~100–150元", "key": "燒臘飯", "m": "D"},
        {"name": "自助餐", "desc": "自選菜色打包走，外食族日常主食", "price": "~75–120元", "key": "自助餐便當", "m": "D"},
        {"name": "豬腳飯", "desc": "滷豬腳膠質滿滿，配酸菜解膩", "price": "~100–150元", "key": "豬腳飯", "m": "D"},
        {"name": "雞肉飯", "desc": "嘉義式雞肉飯，油蔥雞汁超香", "price": "~40–70元", "key": "雞肉飯", "m": "D"},
        {"name": "滷肉飯", "desc": "台灣庶民之光，便宜飽足又療癒", "price": "~35–60元", "key": "滷肉飯", "m": "D"},
        {"name": "超商便當", "desc": "加熱90秒上桌，不用挑不用等", "price": "~55–90元", "key": "超商便當", "m": ""},
        {"name": "咖哩飯", "desc": "日式濃厚咖哩淋白飯，配福神漬超搭", "price": "~100–160元", "key": "咖哩飯", "m": "D"},
        {"name": "燒肉飯", "desc": "炭烤醬燒肉片鋪飯上，鹹香停不下來", "price": "~90–130元", "key": "燒肉飯", "m": "D"},
        {"name": "魯肉飯＋排骨湯", "desc": "滷肉飯加碗排骨湯，台灣人的日常奢華", "price": "~70–100元", "key": "魯肉飯", "m": "D"},
    ],
    "麵食": [
        {"name": "牛肉麵", "desc": "大塊牛腱＋濃郁湯底，台灣魂料理", "price": "~120–200元", "key": "牛肉麵", "m": "D"},
        {"name": "日式拉麵", "desc": "濃厚豚骨湯底，叉燒入口即化", "price": "~200–300元", "key": "拉麵", "m": "D"},
        {"name": "乾麵＋貢丸湯", "desc": "麵攤2分鐘上桌，台灣最快一餐", "price": "~60–85元", "key": "乾麵", "m": "D"},
        {"name": "鍋燒意麵", "desc": "魚板貢丸意麵，暖胃又滿足", "price": "~70–110元", "key": "鍋燒意麵", "m": "D"},
        {"name": "切仔麵", "desc": "湯清麵Q配黑白切，快又飽", "price": "~70–100元", "key": "切仔麵", "m": "D"},
        {"name": "義大利麵", "desc": "白醬紅醬青醬任選，簡餐店好選擇", "price": "~150–250元", "key": "義大利麵", "m": "D"},
        {"name": "涼麵", "desc": "夏天消暑首選，醬汁控制就很清爽", "price": "~60–80元", "key": "涼麵", "m": "D"},
        {"name": "蚵仔麵線", "desc": "滑溜麵線配大腸蚵仔，5分鐘吃完", "price": "~50–75元", "key": "蚵仔麵線", "m": "D"},
        {"name": "越南河粉", "desc": "清湯底蔬菜多，飽足感意外高", "price": "~100–140元", "key": "越南河粉", "m": "D"},
        {"name": "魚片湯麵", "desc": "清湯不油，腸胃弱也能吃", "price": "~100–130元", "key": "魚片湯麵", "m": "D"},
        {"name": "擔仔麵", "desc": "台南經典，肉燥蝦仁小碗精緻", "price": "~50–80元", "key": "擔仔麵", "m": "D"},
        {"name": "米粉湯", "desc": "清湯米粉配黑白切，台式速食", "price": "~40–70元", "key": "米粉湯", "m": "D"},
        {"name": "炒麵", "desc": "醬油炒麵加荷包蛋，簡單但超香", "price": "~50–80元", "key": "炒麵", "m": "D"},
        {"name": "餛飩湯麵", "desc": "薄皮大餡鮮肉餛飩，湯鮮麵Q", "price": "~70–100元", "key": "餛飩麵", "m": "D"},
        {"name": "刀削麵", "desc": "手削厚實麵條，嚼勁十足配牛肉", "price": "~100–150元", "key": "刀削麵", "m": "D"},
    ],
    "小吃": [
        {"name": "蚵仔煎", "desc": "鮮蚵配甜辣醬，夜市經典第一名", "price": "~60–80元", "key": "蚵仔煎", "m": "D"},
        {"name": "臭豆腐", "desc": "台灣魔力食物，聞著考驗吃著上癮", "price": "~60–100元", "key": "臭豆腐", "m": "D"},
        {"name": "肉圓", "desc": "蒸的炸的各有風味，一顆解饞", "price": "~40–60元", "key": "肉圓", "m": "D"},
        {"name": "鹽酥雞", "desc": "夜市靈魂，九層塔蒜頭辣粉缺一不可", "price": "~80–150元", "key": "鹽酥雞", "m": "N"},
        {"name": "雞排", "desc": "超大炸雞排，外酥內嫩一口咬下超爽", "price": "~70–90元", "key": "雞排", "m": "N"},
        {"name": "滷味", "desc": "夾了就走，雞腿海帶豆干自己配", "price": "~80–130元", "key": "滷味攤", "m": "N"},
        {"name": "水餃", "desc": "20顆水餃＋酸辣湯，10分鐘搞定", "price": "~65–90元", "key": "水餃店", "m": "D"},
        {"name": "鍋貼", "desc": "煎得金黃配蛋花湯，10分鐘飽足", "price": "~70–90元", "key": "鍋貼", "m": "D"},
        {"name": "割包", "desc": "台版漢堡，控肉花生粉酸菜", "price": "~50–80元", "key": "刈包", "m": "D"},
        {"name": "胡椒餅", "desc": "炭烤酥皮包蔥肉，排隊也值得", "price": "~50–60元", "key": "胡椒餅", "m": "D"},
        {"name": "肉粽", "desc": "南部粽北部粽，帶著走的飽足感", "price": "~35–60元", "key": "肉粽", "m": ""},
        {"name": "鹹水雞", "desc": "冰鎮雞肉配蒜蓉醬油，夏天必吃涼食", "price": "~80–150元", "key": "鹹水雞", "m": "N"},
        {"name": "潤餅", "desc": "薄皮包花生粉豆芽蛋酥，清明不限定", "price": "~50–70元", "key": "潤餅", "m": "D"},
        {"name": "蔥油餅", "desc": "煎到金黃酥脆，加蛋更邪惡", "price": "~30–50元", "key": "蔥油餅", "m": "D"},
        {"name": "大腸包小腸", "desc": "糯米腸夾香腸，夜市雙拼經典", "price": "~60–80元", "key": "大腸包小腸", "m": "N"},
        {"name": "豬血糕", "desc": "花生粉香菜醬油膏，外國人怕台灣人愛", "price": "~30–50元", "key": "豬血糕", "m": "D"},
        {"name": "碗粿", "desc": "軟嫩米漿蒸糕配醬油膏，南部經典", "price": "~30–50元", "key": "碗粿", "m": "D"},
        {"name": "筒仔米糕", "desc": "糯米蒸進竹筒，配甜辣醬超對味", "price": "~40–60元", "key": "筒仔米糕", "m": "D"},
        {"name": "地瓜球", "desc": "QQ彈彈炸地瓜球，越吃越涮嘴", "price": "~40–60元", "key": "地瓜球", "m": "D"},
        {"name": "關東煮", "desc": "蘿蔔竹輪魚板，暖呼呼一碗搞定", "price": "~50–80元", "key": "關東煮", "m": "D"},
        {"name": "車輪餅", "desc": "奶油紅豆芋頭，銅板甜點隨買隨吃", "price": "~15–25元", "key": "車輪餅", "m": "D"},
        {"name": "香腸", "desc": "烤得焦香配蒜頭，夜市散步必拿", "price": "~40–60元", "key": "烤香腸", "m": "N"},
    ],
    "火鍋": [
        {"name": "個人小火鍋", "desc": "一個人也能吃，湯底自選料夠多", "price": "~150–250元", "key": "個人小火鍋", "m": "D"},
        {"name": "麻辣鍋", "desc": "又麻又辣出一身汗，壓力全釋放", "price": "~300–500元", "key": "麻辣鍋", "m": "N"},
        {"name": "薑母鴨", "desc": "米酒薑香暖身，秋冬必吃", "price": "~300–450元", "key": "薑母鴨", "m": "N"},
        {"name": "羊肉爐", "desc": "當歸薑片羊肉湯，冬天暖身首選", "price": "~250–400元", "key": "羊肉爐", "m": "N"},
        {"name": "酸菜白肉鍋", "desc": "酸菜湯底配白肉，清爽解膩", "price": "~250–400元", "key": "酸菜白肉鍋", "m": "N"},
        {"name": "韓式豆腐鍋", "desc": "豆腐蔬菜蛋，低卡高蛋白暖胃", "price": "~150–200元", "key": "韓式豆腐鍋", "m": "D"},
        {"name": "海鮮鍋", "desc": "蝦蟹蛤蜊鮮甜湯底，海味滿滿", "price": "~300–500元", "key": "海鮮火鍋", "m": "N"},
        {"name": "涮涮鍋", "desc": "一人一鍋現涮現吃，清湯養生", "price": "~200–350元", "key": "涮涮鍋", "m": "D"},
        {"name": "壽喜燒", "desc": "甜鹹醬汁涮牛肉裹蛋液，日式經典", "price": "~300–500元", "key": "壽喜燒", "m": "N"},
        {"name": "麻油雞", "desc": "麻油薑香暖全身，冬天進補首選", "price": "~200–350元", "key": "麻油雞", "m": "N"},
        {"name": "泡菜鍋", "desc": "韓式辣泡菜配豬肉豆腐，酸辣開胃", "price": "~150–250元", "key": "泡菜鍋", "m": "D"},
        {"name": "牛奶鍋", "desc": "濃郁奶香湯底，小朋友也愛", "price": "~200–300元", "key": "牛奶鍋", "m": "D"},
    ],
    "日韓": [
        {"name": "壽司", "desc": "迴轉壽司或超商壽司，清爽方便", "price": "~60–300元", "key": "壽司", "m": ""},
        {"name": "日式丼飯", "desc": "牛丼親子丼豬排丼，一碗搞定", "price": "~120–200元", "key": "丼飯", "m": "D"},
        {"name": "日式定食", "desc": "烤魚豆腐套餐，蒸煮為主蔬菜豐富", "price": "~150–200元", "key": "日式定食", "m": "D"},
        {"name": "韓式炸雞", "desc": "外酥內嫩甜辣醬，越吃越停不下來", "price": "~200–300元", "key": "韓式炸雞", "m": "N"},
        {"name": "燒肉", "desc": "日式燒肉配飯配味噌湯，超滿足", "price": "~200–400元", "key": "燒肉定食", "m": "N"},
        {"name": "咖哩飯", "desc": "日式咖哩配白飯，一盤解決", "price": "~120–180元", "key": "咖哩飯", "m": "D"},
        {"name": "居酒屋", "desc": "下班小酌串燒配啤酒，辛苦值了", "price": "~300–500元", "key": "居酒屋", "m": "N"},
        {"name": "韓式拌飯", "desc": "石鍋拌飯蔬菜蛋肉均衡，營養滿分", "price": "~150–250元", "key": "韓式拌飯", "m": "D"},
        {"name": "炸豬排", "desc": "厚切酥炸豬排配高麗菜絲，吃完超滿足", "price": "~180–280元", "key": "炸豬排", "m": "D"},
        {"name": "天婦羅", "desc": "炸蝦炸蔬菜輕薄酥脆，沾醬油最對味", "price": "~150–250元", "key": "天婦羅", "m": "D"},
        {"name": "鰻魚飯", "desc": "蒲燒鰻魚配醬汁飯，奢華但值得", "price": "~300–500元", "key": "鰻魚飯", "m": "D"},
        {"name": "生魚片丼", "desc": "新鮮生魚片鋪滿醋飯，海味滿滿", "price": "~200–400元", "key": "生魚片丼", "m": "D"},
        {"name": "部隊鍋", "desc": "泡麵年糕香腸起司大雜燴，韓式暖胃", "price": "~250–400元", "key": "部隊鍋", "m": "N"},
    ],
    "早午餐": [
        {"name": "蛋餅＋豆漿", "desc": "台灣人的晨間能量補給站", "price": "~45–70元", "key": "早餐店", "m": "M"},
        {"name": "飯糰", "desc": "糯米飯糰帶著走，咬一口很扎實", "price": "~35–60元", "key": "飯糰", "m": "M"},
        {"name": "蘿蔔糕", "desc": "煎得金黃，早餐店經典", "price": "~30–50元", "key": "蘿蔔糕", "m": "M"},
        {"name": "蔥抓餅加蛋", "desc": "酥脆又飽足，3分鐘出餐", "price": "~40–55元", "key": "蔥抓餅", "m": "M"},
        {"name": "燒餅油條", "desc": "傳統中式早餐，配鹹豆漿最對味", "price": "~40–60元", "key": "燒餅油條", "m": "M"},
        {"name": "鹹豆漿＋燒餅", "desc": "豆漿配油條燒餅，吃超飽", "price": "~60–90元", "key": "鹹豆漿 燒餅", "m": "M"},
        {"name": "碗粿＋魚丸湯", "desc": "米漿碗粿配熱湯，溫潤不油", "price": "~55–80元", "key": "碗粿", "m": "M"},
        {"name": "漢堡＋奶茶", "desc": "西式早餐店套餐，簡單快速", "price": "~60–100元", "key": "早午餐", "m": "M"},
        {"name": "三明治＋紅茶", "desc": "帶著走的最速配組合", "price": "~50–80元", "key": "三明治", "m": "M"},
        {"name": "粥品", "desc": "清淡好消化，早餐吃粥最養胃", "price": "~50–80元", "key": "粥 台式", "m": "M"},
        {"name": "鬆餅早午餐", "desc": "鬆餅配培根蛋，假日慢慢吃", "price": "~150–250元", "key": "鬆餅 早午餐", "m": "M"},
        {"name": "可頌三明治", "desc": "酥脆可頌夾火腿起司，法式早餐", "price": "~80–130元", "key": "可頌", "m": "M"},
        {"name": "法式吐司", "desc": "蛋液浸吐司煎到金黃，淋蜂蜜楓糖", "price": "~100–180元", "key": "法式吐司", "m": "M"},
    ],
    "飲料甜點": [
        {"name": "珍珠奶茶", "desc": "台灣國飲，心情不好來一杯就解決", "price": "~50–80元", "key": "珍珠奶茶", "m": "", "s": ""},
        {"name": "咖啡", "desc": "美式拿鐵卡布，提神醒腦必備", "price": "~50–150元", "key": "咖啡廳", "m": "", "s": ""},
        {"name": "蛋糕甜點", "desc": "蛋糕配咖啡犒賞自己，超療癒", "price": "~100–200元", "key": "蛋糕店", "m": "", "s": ""},
        {"name": "豆花", "desc": "綿密豆花加花生粉圓，古早味甜品", "price": "~40–60元", "key": "豆花", "m": "D", "s": ""},
        {"name": "鮮奶茶", "desc": "用鮮奶不用奶精，喝起來就是不一樣", "price": "~55–80元", "key": "鮮奶茶", "m": "", "s": ""},
        {"name": "果汁", "desc": "現打果汁補充維他命，健康解渴", "price": "~50–80元", "key": "現打果汁", "m": "", "s": ""},
        {"name": "抹茶拿鐵", "desc": "日本宇治抹茶配鮮奶，苦甜平衡剛好", "price": "~80–130元", "key": "抹茶拿鐵", "m": "", "s": ""},
        {"name": "楊枝甘露", "desc": "芒果椰汁西米露，港式甜品經典", "price": "~80–150元", "key": "港式甜品", "m": "D", "s": ""},
        {"name": "手搖飲", "desc": "四季春烏龍鮮奶茶，下午三點必來一杯", "price": "~40–70元", "key": "手搖飲", "m": "", "s": ""},
        # 夏天限定 (5-10月)
        {"name": "剉冰", "desc": "芒果冰紅豆冰，台灣夏天消暑第一名", "price": "~50–100元", "key": "剉冰", "m": "D", "s": "hot"},
        {"name": "愛玉檸檬", "desc": "現搖愛玉配新鮮檸檬汁，夏日必喝", "price": "~40–65元", "key": "愛玉", "m": "D", "s": "hot"},
        {"name": "仙草凍飲", "desc": "仙草加鮮奶清涼退火，夏天消暑聖品", "price": "~45–65元", "key": "仙草", "m": "", "s": "hot"},
        {"name": "冰淇淋", "desc": "義式濃縮口味多樣，夏日隨心情換口味", "price": "~80–180元", "key": "冰淇淋", "m": "D", "s": "hot"},
        {"name": "楊桃汁", "desc": "古早味鹹楊桃汁，台南夏日傳統飲料", "price": "~30–50元", "key": "楊桃汁", "m": "D", "s": "hot"},
        {"name": "粉粿冰", "desc": "台南古早粉粿加黑糖，消暑又扎實", "price": "~40–70元", "key": "粉粿冰", "m": "D", "s": "hot"},
        # 冬天限定 (11-4月)
        {"name": "燒仙草", "desc": "熱燒仙草配芋圓湯圓，冬天最暖心", "price": "~50–80元", "key": "燒仙草", "m": "D", "s": "cold"},
        {"name": "紅豆湯＋湯圓", "desc": "冬至必吃，暖呼呼甜湯補充元氣", "price": "~40–70元", "key": "紅豆湯 湯圓", "m": "D", "s": "cold"},
        {"name": "花生湯", "desc": "綿密花生甜湯，古早味暖胃甜品", "price": "~40–60元", "key": "花生湯", "m": "D", "s": "cold"},
        {"name": "薑母茶", "desc": "老薑麻油糖，手腳冰冷喝了馬上暖", "price": "~50–80元", "key": "薑母茶", "m": "D", "s": "cold"},
        {"name": "熱可可", "desc": "濃郁巧克力配棉花糖，冬天療癒聖品", "price": "~80–150元", "key": "熱可可 巧克力", "m": "", "s": "cold"},
        {"name": "地瓜湯圓", "desc": "薑汁地瓜配小湯圓，甜蜜蜜暖意滿滿", "price": "~40–65元", "key": "地瓜湯圓", "m": "D", "s": "cold"},
    ],
    "輕食": [
        {"name": "沙拉", "desc": "雞胸肉沙拉，超商或輕食店都有", "price": "~80–150元", "key": "沙拉 輕食", "m": ""},
        {"name": "御飯糰", "desc": "超商三角飯糰，帶著走最方便", "price": "~25–40元", "key": "御飯糰", "m": ""},
        {"name": "關東煮", "desc": "超商自選配料，控制熱量又暖胃", "price": "~50–80元", "key": "關東煮", "m": ""},
        {"name": "烤地瓜", "desc": "超商健康選擇，飽足感高熱量低", "price": "~35–55元", "key": "烤地瓜", "m": ""},
        {"name": "優格", "desc": "膳食纖維補充站，早餐下午茶都適合", "price": "~40–70元", "key": "優格", "m": ""},
        {"name": "燕麥飲", "desc": "膳食纖維＋低糖，健康族首選", "price": "~30–50元", "key": "燕麥牛奶", "m": ""},
        {"name": "水煮餐", "desc": "健身族最愛，雞胸花椰菜糙米", "price": "~100–150元", "key": "水煮餐", "m": "D"},
        {"name": "蔬食便當", "desc": "素食自助餐，自選蔬菜控制油量", "price": "~80–110元", "key": "素食自助餐", "m": "D"},
        {"name": "貝果", "desc": "嚼勁十足配酪梨或鮪魚，健康又飽足", "price": "~60–120元", "key": "貝果", "m": "M"},
        {"name": "雞胸肉便當", "desc": "低脂高蛋白，健身族外食首選", "price": "~100–150元", "key": "健身餐", "m": "D"},
        {"name": "豆腐料理", "desc": "涼拌豆腐或紅燒豆腐，高蛋白低熱量", "price": "~60–100元", "key": "豆腐料理", "m": "D"},
    ],
    "台式早餐": [
        {"name": "蛋餅", "desc": "外皮酥脆蛋香濃，加起司或鮪魚更滿足", "price": "~30–55元", "key": "蛋餅 台式早餐", "m": "M"},
        {"name": "飯糰", "desc": "糯米包油條肉鬆，台灣人記憶中的早晨", "price": "~35–55元", "key": "飯糰 台式", "m": "M"},
        {"name": "燒餅油條", "desc": "酥脆燒餅夾油條，配豆漿是完美早餐", "price": "~25–45元", "key": "燒餅油條", "m": "M"},
        {"name": "豆漿＋燒餅", "desc": "鹹甜豆漿配燒餅油條，台式早點經典組合", "price": "~40–60元", "key": "豆漿 燒餅 早點", "m": "M"},
        {"name": "蘿蔔糕", "desc": "香煎蘿蔔糕外脆內軟，沾醬油膏超下飯", "price": "~25–40元", "key": "蘿蔔糕 台式早餐", "m": "M"},
        {"name": "鹹豆漿", "desc": "滾燙豆漿加蝦皮榨菜油條，鹹香暖胃", "price": "~30–45元", "key": "鹹豆漿", "m": "M"},
        {"name": "吐司三明治", "desc": "台式吐司夾蛋火腿，早餐店必點快速飽腹", "price": "~30–50元", "key": "吐司 早餐店", "m": "M"},
    ],
    "西式早餐": [
        {"name": "班尼迪克蛋", "desc": "水波蛋配荷蘭醬，週末Brunch的儀式感", "price": "~180–350元", "key": "班尼迪克蛋 brunch", "m": "M"},
        {"name": "法式吐司", "desc": "蛋液浸泡後煎到金黃，配楓糖漿超幸福", "price": "~120–220元", "key": "法式吐司", "m": "M"},
        {"name": "歐姆蛋", "desc": "蓬鬆歐式炒蛋，配培根生菜豐盛又滿足", "price": "~150–280元", "key": "歐姆蛋 早午餐", "m": "M"},
        {"name": "美式大早餐", "desc": "荷包蛋培根香腸烤番茄全包，超澎湃", "price": "~200–380元", "key": "美式早餐 brunch", "m": "M"},
        {"name": "可頌三明治", "desc": "酥脆可頌夾火腿起司，法式早餐的優雅", "price": "~120–200元", "key": "可頌 三明治", "m": "M"},
        {"name": "鬆餅", "desc": "厚鬆餅配鮮奶油草莓，Instagram必拍早午餐", "price": "~150–280元", "key": "鬆餅 早午餐", "m": "M"},
    ],
    "燒烤": [
        {"name": "日式串燒", "desc": "雞腿雞皮軟骨烤到恰到好處，配生啤最對味", "price": "~150–350元", "key": "串燒 燒烤", "m": "N"},
        {"name": "韓式烤肉", "desc": "五花肉豬頸肉生菜包著吃，韓式辣醬畫龍點睛", "price": "~300–600元", "key": "韓式烤肉 燒肉", "m": "N"},
        {"name": "炭烤雞腿", "desc": "炭火慢烤雞腿，皮脆肉嫩煙燻香氣", "price": "~100–180元", "key": "炭烤 雞腿", "m": "DN"},
        {"name": "鹽烤豬五花", "desc": "薄切五花肉撒海鹽，油脂滲出香氣四溢", "price": "~200–400元", "key": "日式燒肉 五花", "m": "N"},
        {"name": "BBQ串燒", "desc": "各式蔬菜肉串輪番上烤架，配啤酒超爽", "price": "~200–500元", "key": "BBQ 燒烤", "m": "N"},
    ],
    "港式": [
        {"name": "港式飲茶", "desc": "蝦餃燒賣叉燒包輪流點，熱鬧又滿足", "price": "~200–500元", "key": "港式飲茶 點心", "m": "MD"},
        {"name": "燒臘飯", "desc": "叉燒燒鴨雙拼油飯，港式快餐的靈魂", "price": "~120–200元", "key": "燒臘飯 叉燒", "m": "D"},
        {"name": "叉燒酥", "desc": "酥脆外皮包甜鹹叉燒，港點午茶必點", "price": "~40–80元", "key": "叉燒酥 港點", "m": "MD"},
        {"name": "蝦餃皇", "desc": "薄皮透明包大蝦，鮮甜Q彈港點之王", "price": "~80–150元", "key": "蝦餃 港式", "m": "MD"},
        {"name": "腸粉", "desc": "滑嫩米皮卷蝦仁叉燒，淋上蠔油超香", "price": "~60–120元", "key": "腸粉 港式", "m": "MD"},
        {"name": "菠蘿油", "desc": "港式菠蘿包夾厚奶油，奶香酥脆下午茶", "price": "~40–70元", "key": "菠蘿包 港式", "m": "M"},
    ],
    "義式": [
        {"name": "卡波內拉義大利麵", "desc": "Carbonara蛋黃起司培根麵，濃郁不膩", "price": "~180–280元", "key": "義大利麵 Carbonara", "m": "DN"},
        {"name": "番茄肉醬麵", "desc": "自製番茄醬慢燉牛肉，義式料理基本款", "price": "~160–260元", "key": "義大利麵 番茄肉醬", "m": "DN"},
        {"name": "瑪格麗特披薩", "desc": "薄脆餅皮配新鮮番茄莫扎瑞拉，義式經典", "price": "~200–380元", "key": "披薩 義式", "m": "DN"},
        {"name": "燉飯", "desc": "義大利米慢煮到奶油香，菇類或海鮮口味", "price": "~200–350元", "key": "義式燉飯", "m": "DN"},
        {"name": "青醬義大利麵", "desc": "羅勒松子製成青醬配天使麵，清新不油膩", "price": "~170–270元", "key": "青醬 義大利麵", "m": "DN"},
    ],
    "素食": [
        {"name": "素食自助餐", "desc": "多種蔬食選擇自由配，健康低卡又飽足", "price": "~80–120元", "key": "素食自助餐", "m": "D"},
        {"name": "蔬食便當", "desc": "豆腐滷蛋蔬菜均衡搭配，外食族養生首選", "price": "~80–130元", "key": "蔬食便當", "m": "D"},
        {"name": "素拉麵", "desc": "蔬菜高湯底配豆皮木耳，清爽不油膩", "price": "~100–160元", "key": "素食拉麵", "m": "DN"},
        {"name": "素食涮涮鍋", "desc": "菇類豆腐豆皮加蔬菜，清爽好消化", "price": "~150–280元", "key": "素食火鍋 蔬食", "m": "N"},
        {"name": "素食炒飯", "desc": "蔬菜炒飯加豆腐，簡單扎實不油膩", "price": "~80–120元", "key": "素食炒飯", "m": "D"},
    ],
    "粥": [
        {"name": "廣式皮蛋瘦肉粥", "desc": "濃稠廣式粥底配皮蛋豬肉絲，早餐最暖胃", "price": "~60–100元", "key": "廣式粥 皮蛋瘦肉粥", "m": "ML"},
        {"name": "台式稀飯", "desc": "清淡米粥配蘿蔔乾豆腐乳，台灣阿嬤的味道", "price": "~40–70元", "key": "台式稀飯", "m": "ML"},
        {"name": "鮮魚粥", "desc": "新鮮魚片配薑絲，清甜鮮美不腥", "price": "~80–150元", "key": "鮮魚粥", "m": "ML"},
        {"name": "豬肚粥", "desc": "豬肚切片配薑蔥粥底，暖身又補胃", "price": "~80–130元", "key": "豬肚粥", "m": "ML"},
        {"name": "地瓜粥", "desc": "甜地瓜配白粥，台灣古早味健康選擇", "price": "~40–65元", "key": "地瓜粥", "m": "ML"},
    ],
    "麵包蛋糕": [
        {"name": "可頌", "desc": "法式千層酥脆可頌，奶油香氣撲鼻", "price": "~45–90元", "key": "可頌 麵包店", "m": "M"},
        {"name": "手工吐司", "desc": "厚切生吐司配奶油，台灣烘焙近年爆紅", "price": "~50–100元", "key": "生吐司 厚片", "m": "M"},
        {"name": "起司蛋糕", "desc": "輕乳酪蛋糕入口即化，下午茶首選甜點", "price": "~60–150元", "key": "起司蛋糕 烘焙", "m": ""},
        {"name": "貝果", "desc": "嚼勁十足配奶油乳酪，低脂又飽足感強", "price": "~50–120元", "key": "貝果 烘焙坊", "m": "M"},
        {"name": "蛋糕捲", "desc": "鬆軟戚風蛋糕捲配鮮奶油，台灣甜點界人氣王", "price": "~80–180元", "key": "蛋糕捲 甜點", "m": ""},
    ],
    "夜市小吃": [
        {"name": "鹽酥雞", "desc": "九層塔炸物飄香，台灣夜市永遠的王者", "price": "~50–120元", "key": "鹽酥雞 夜市", "m": "NL"},
        {"name": "大腸包小腸", "desc": "糯米腸夾香腸酸菜，台灣夜市限定幸福感", "price": "~50–80元", "key": "大腸包小腸 夜市", "m": "NL"},
        {"name": "蚵仔煎", "desc": "肥美蚵仔米漿皮加甜辣醬，夜市必吃之王", "price": "~50–80元", "key": "蚵仔煎 夜市", "m": "NL"},
        {"name": "臭豆腐", "desc": "越臭越香外酥內嫩，配泡菜才是正確吃法", "price": "~40–70元", "key": "臭豆腐 夜市", "m": "NL"},
        {"name": "關東煮", "desc": "甜不辣蘿蔔豬血糕輪流夾，消夜最療癒", "price": "~30–70元", "key": "關東煮 夜市", "m": "NL"},
        {"name": "章魚燒", "desc": "外酥內軟章魚球，柴魚美乃滋香氣撲鼻", "price": "~40–70元", "key": "章魚燒 夜市", "m": "NL"},
    ],
    "炸物": [
        {"name": "炸雞排", "desc": "台灣超大片雞排外酥內嫩，加椒鹽超過癮", "price": "~60–100元", "key": "炸雞排", "m": "NL"},
        {"name": "鹽酥雞攤", "desc": "自選食材油炸，九層塔香氣無法抵擋", "price": "~50–120元", "key": "鹽酥雞", "m": "NL"},
        {"name": "炸甜不辣", "desc": "魚漿炸物沾甜辣醬，台灣消夜定番", "price": "~30–60元", "key": "甜不辣 炸物", "m": "NL"},
        {"name": "炸豬排飯", "desc": "日式豬排炸到金黃，淋柔煎醬配白飯超滿足", "price": "~120–180元", "key": "炸豬排 豬排飯", "m": "DN"},
        {"name": "地瓜球", "desc": "外脆內軟地瓜球，夜市跟炸物攤必點", "price": "~30–50元", "key": "地瓜球", "m": "NL"},
    ],
    "拉麵": [
        {"name": "豚骨拉麵", "desc": "濃厚豬骨湯底煮12小時以上，叉燒入口即化", "price": "~200–350元", "key": "豚骨拉麵", "m": "DN"},
        {"name": "醬油拉麵", "desc": "清爽醬油湯底，烤海苔溏心蛋標配", "price": "~180–300元", "key": "醬油拉麵", "m": "DN"},
        {"name": "味噌拉麵", "desc": "北海道風濃厚味噌湯，玉米奶油加分", "price": "~200–350元", "key": "味噌拉麵", "m": "DN"},
        {"name": "沾麵", "desc": "濃縮醬汁沾Q彈麵條，拉麵控必試", "price": "~200–350元", "key": "沾麵 拉麵", "m": "DN"},
        {"name": "辣味拉麵", "desc": "麻辣湯底配爽脆蔬菜，刺激又過癮", "price": "~200–320元", "key": "辣味拉麵", "m": "DN"},
        {"name": "乾拌拉麵", "desc": "不要湯的拌麵版本，醬汁拌到每根麵都入味", "price": "~180–280元", "key": "乾拌拉麵", "m": "DN"},
    ],
}  # fallback

# ── 米其林必比登推介（由 update_bib_in_webhook.py 自動更新）──
_BIB_GOURMAND: dict = _load_json("bib_gourmand.json", {})
if not _BIB_GOURMAND:
    _BIB_GOURMAND = {
    "台北": [
        {"name": "胖塔可", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taipei-region/taipei/restaurant/pang"},
        {"name": "Tableau by Craig Yang", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taipei-region/taipei/restaurant/tableau-by-craig-yang"},
        {"name": "巷子龍家常菜", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taipei-region/taipei/restaurant/talking-heads"},
        {"name": "醉楓園小館", "type": "", "desc": "松山區｜米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taipei-region/taipei/restaurant/tsui-feng-yuan"},
        {"name": "天下三絕", "type": "", "desc": "大安區｜米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taipei-region/taipei/restaurant/tien-hsia-san-chueh"},
        {"name": "小小樹食 (大安路)", "type": "", "desc": "大安區｜米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taipei-region/taipei/restaurant/little-tree-food-da-an-road"},
        {"name": "金賞軒", "type": "", "desc": "松山區｜米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taipei-region/taipei/restaurant/jin-shang-hsuan"},
        {"name": "茂園", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taipei-region/taipei/restaurant/mao-yuan"},
        {"name": "雲川水月", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taipei-region/taipei/restaurant/clavius"},
        {"name": "鼎泰豐 (信義路)", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taipei-region/taipei/restaurant/din-tai-fung-xinyi-road"},
        {"name": "軟食力", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taipei-region/taipei/restaurant/soft-power"},
        {"name": "雄記蔥抓餅", "type": "", "desc": "中正區｜米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taipei-region/taipei/restaurant/hsiung-chi-scallion-pancake"},
        {"name": "杭州小籠湯包 (大安)", "type": "", "desc": "大安區｜米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taipei-region/taipei/restaurant/hang-zhou-xiao-long-bao-da-an"},
        {"name": "雞家莊 (長春路)", "type": "", "desc": "中山區｜米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taipei-region/taipei/restaurant/chi-chia-chuang-changchun-road"},
        {"name": "雙月食品 (青島東路)", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taipei-region/taipei/restaurant/shuang-yue-food"},
        {"name": "祥和蔬食 (中正)", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taipei-region/taipei/restaurant/serenity"},
        {"name": "小品雅廚", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taipei-region/taipei/restaurant/xiao-ping-kitchen"},
        {"name": "小酌之家", "type": "", "desc": "中山區｜米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taipei-region/taipei/restaurant/hsiao-cho-chih-chia"},
        {"name": "人和園", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taipei-region/taipei/restaurant/jen-ho-yuan"},
        {"name": "黃記魯肉飯", "type": "", "desc": "中山區｜米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taipei-region/taipei/restaurant/huang-chi-lu-rou-fan"},
        {"name": "隱食家", "type": "", "desc": "中山區｜米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taipei-region/taipei/restaurant/inn-s"},
        {"name": "宋朝", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/northern-taiwan/new-taipei-city_2853082/restaurant/song-jhao"},
        {"name": "欣葉小聚 (南港)", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taipei-region/taipei/restaurant/shin-yeh-shiao-ju-nangang"},
        {"name": "無名推車燒餅", "type": "", "desc": "中正區｜米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taipei-region/taipei/restaurant/unnamed-clay-oven-roll"},
        {"name": "老山東牛肉家常麵店", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taipei-region/taipei/restaurant/lao-shan-dong-homemade-noodles"},
        {"name": "吾旺再季", "type": "", "desc": "中正區｜米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taipei-region/taipei/restaurant/wu-wang-tsai-chi"},
        {"name": "賣麵炎仔", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taipei-region/taipei/restaurant/mai-mien-yen-tsai"},
        {"name": "大橋頭老牌筒仔米糕 (延平北路)", "type": "", "desc": "大同區｜米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taipei-region/taipei/restaurant/da-qiao-tou-tube-rice-pudding"},
        {"name": "HUGH dessert dining", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taipei-region/taipei/restaurant/hugh"},
        {"name": "阿爸の芋圓", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/northern-taiwan/new-taipei-city_2853082/restaurant/a-ba-s-taro-ball"},
        {"name": "一甲子餐飲", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taipei-region/taipei/restaurant/yi-jia-zi"},
        {"name": "客家小館", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/northern-taiwan/new-taipei-city_2853082/restaurant/garden-h"},
        {"name": "永和佳香豆漿", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/northern-taiwan/new-taipei-city_2853082/restaurant/yonghe-chia-hsiang-soy-milk"},
        {"name": "蔡家牛肉麵", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/northern-taiwan/new-taipei-city_2853082/restaurant/tsai-chia-beef-noodles"},
        {"name": "源芳刈包", "type": "", "desc": "萬華區｜米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taipei-region/taipei/restaurant/yuan-fang-guabao"},
        {"name": "小王煮瓜", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taipei-region/taipei/restaurant/hsiao-wang-steamed-minced-pork-with-pickles-in-broth"},
        {"name": "蘇來傳", "type": "", "desc": "萬華區｜米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taipei-region/taipei/restaurant/su-lai-chuan"},
        {"name": "鍾家原上海生煎包", "type": "", "desc": "士林區｜米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taipei-region/taipei/restaurant/chung-chia-sheng-jian-bao"},
        {"name": "好朋友涼麵", "type": "", "desc": "士林區｜米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taipei-region/taipei/restaurant/good-friend-cold-noodles"},
        {"name": "店小二 (大同北路)", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/northern-taiwan/new-taipei-city_2853082/restaurant/dian-xiao-er-datong-north-road"},
        {"name": "賴岡山羊肉", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/northern-taiwan/new-taipei-city_2853082/restaurant/lai-kang-shan"},
        {"name": "山東小館", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/northern-taiwan/new-taipei-city_2853082/restaurant/san-tung"},
        {"name": "超人鱸魚", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/northern-taiwan/new-taipei-city_2853082/restaurant/superman"},
        {"name": "光興腿庫", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/northern-taiwan/new-taipei-city_2853082/restaurant/guang-xing-pork-knuckle"},
        {"name": "葉家藥燉排骨", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/northern-taiwan/new-taipei-city_2853082/restaurant/yeh-chia-pork-ribs-medicinal-herbs-soup"},
        {"name": "番紅花印度美饌", "type": "", "desc": "士林區｜米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taipei-region/taipei/restaurant/saffron"},
        {"name": "上好雞肉", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/northern-taiwan/new-taipei-city_2853082/restaurant/shang-hao"},
        {"name": "松竹園", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taipei-region/taipei/restaurant/sung-chu-yuan"},
        {"name": "珍品餐飲坊", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/northern-taiwan/new-taipei-city_2853082/restaurant/jhen-pin"},
        {"name": "三姐妹農家樂", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/northern-taiwan/new-taipei-city_2853082/restaurant/san-chieh-mei-nung-chia-le"},
    ],
    "台中": [
        {"name": "曙光居", "type": "", "desc": "西屯區｜米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taichung-region/taichung/restaurant/house-of-dawn"},
        {"name": "可口牛肉麵", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taichung-region/taichung/restaurant/ke-kou-beef-noodles"},
        {"name": "裡小樓", "type": "", "desc": "西屯區｜米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taichung-region/taichung/restaurant/li-xiao-lou"},
        {"name": "夜間部爌肉飯", "type": "", "desc": "西區｜米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taichung-region/taichung/restaurant/night-school-braised-pork-rice"},
        {"name": "功夫上海手工魚丸", "type": "", "desc": "西區｜米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taichung-region/taichung/restaurant/kung-fu-shanghai-fish-ball"},
        {"name": "富狀元豬腳", "type": "", "desc": "西區｜米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taichung-region/taichung/restaurant/fu-juang-yuan"},
        {"name": "羅家古早味 (南屯)", "type": "", "desc": "南屯區｜米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taichung-region/taichung/restaurant/lou-s-nantun"},
        {"name": "繡球", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taichung-region/taichung/restaurant/ajisai"},
        {"name": "滬舍餘味 (南屯)", "type": "", "desc": "南屯區｜米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taichung-region/taichung/restaurant/shanghai-food"},
        {"name": "好菜 (西區)", "type": "", "desc": "西區｜米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taichung-region/taichung/restaurant/kuisine"},
        {"name": "馨苑 (西區)", "type": "台菜", "desc": "西區｜米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taichung-region/taichung/restaurant/shin-yuan"},
        {"name": "富鼎旺 (中區)", "type": "", "desc": "中區｜米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taichung-region/taichung/restaurant/fu-din-wang-central"},
        {"name": "富貴亭", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taichung-region/taichung/restaurant/fu-kuei-ting"},
        {"name": "阿坤麵", "type": "", "desc": "中區｜米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taichung-region/taichung/restaurant/a-kun-mian"},
        {"name": "上海未名麵點", "type": "", "desc": "中區｜米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taichung-region/taichung/restaurant/no-name-noodles"},
        {"name": "范記金之園 (中區)", "type": "", "desc": "中區｜米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taichung-region/taichung/restaurant/chin-chih-yuan"},
        {"name": "醉月樓", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taichung-region/taichung/restaurant/moon-pavilion"},
        {"name": "台中肉員", "type": "", "desc": "南區｜米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taichung-region/taichung/restaurant/taichung-meatball"},
        {"name": "彭城堂", "type": "台菜", "desc": "太平區｜米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taichung-region/taichung/restaurant/peng-cheng-tang"},
        {"name": "鳳記鵝肉老店", "type": "", "desc": "沙鹿區｜米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taichung-region/taichung/restaurant/feng-chi-goose"},
        {"name": "老士官擀麵", "type": "", "desc": "清水區｜米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taichung-region/taichung/restaurant/lao-shih-kuan-noodles"},
        {"name": "牛稼莊", "type": "", "desc": "東勢區｜米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taichung-region/taichung/restaurant/niou-jia-juang"},
        {"name": "鮨承", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taichung-region/taichung/restaurant/sushi-noru"},
        {"name": "肉料理 · 福", "type": "", "desc": "北區｜米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/taichung-region/taichung/restaurant/niku-ryouri-fuku"},
    ],
    "台南": [
        {"name": "大勇街無名鹹粥", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/tainan-region/tainan/restaurant/dayong-street-no-name-congee"},
        {"name": "吃麵吧", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/tainan-region/tainan/restaurant/jai-mi-ba"},
        {"name": "阿文米粿", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/tainan-region/tainan/restaurant/a-wen-rice-cake"},
        {"name": "無名羊肉湯", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/tainan-region/tainan/restaurant/no-name-lamb-soup"},
        {"name": "阿星鹹粥", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/tainan-region/tainan/restaurant/a-hsing-congee"},
        {"name": "八寶彬圓仔惠 (國華街)", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/tainan-region/tainan/restaurant/yuan-zai-hui-guohua-street"},
        {"name": "葉家小卷米粉", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/tainan-region/tainan/restaurant/yeh-jia-calamari-rice-noodle-soup"},
        {"name": "誠實鍋燒意麵", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/tainan-region/tainan/restaurant/cheng-shi"},
        {"name": "筑馨居", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/tainan-region/tainan/restaurant/zhu-xin-ju"},
        {"name": "黃家蝦捲", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/tainan-region/tainan/restaurant/huang-chia-shrimp-roll"},
        {"name": "一味品", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/tainan-region/tainan/restaurant/yi-wei-pin"},
        {"name": "好農家米糕", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/tainan-region/tainan/restaurant/hao-nung-chia-migao"},
        {"name": "小公園擔仔麵", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/tainan-region/tainan/restaurant/small-park-danzai-noodles"},
        {"name": "博仁堂", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/tainan-region/tainan/restaurant/po-jen-tang"},
        {"name": "添厚", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/tainan-region/tainan/restaurant/eat-to-fat"},
        {"name": "阿興虱目魚", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/tainan-region/tainan/restaurant/a-xing-shi-mu-yu"},
        {"name": "落成米糕", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/tainan-region/tainan/restaurant/lo-cheng-migao"},
        {"name": "福泰飯桌第三代", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/tainan-region/tainan/restaurant/fu-tai-table-third-generation"},
        {"name": "麥謎食驗室", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/tainan-region/tainan/restaurant/bue-mi-lab"},
        {"name": "謝掌櫃", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/tainan-region/tainan/restaurant/xie-shopkeeper"},
        {"name": "西羅殿牛肉湯", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/tainan-region/tainan/restaurant/hsi-lo-tien-beef-soup"},
        {"name": "三好一公道當歸鴨", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/tainan-region/tainan/restaurant/san-hao-yi-kung-tao-angelica-duck"},
        {"name": "尚好吃牛肉湯", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/tainan-region/tainan/restaurant/shang-hao-chih-beef-soup"},
        {"name": "葉桑生炒鴨肉焿", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/tainan-region/tainan/restaurant/yeh-san-duck-thick-soup"},
        {"name": "開元紅燒土魠魚羮", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/tainan-region/tainan/restaurant/kaiyuan-fried-spanish-mackerel-thick-soup"},
        {"name": "鮮蒸蝦仁肉圓", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/tainan-region/tainan/restaurant/shian-jeng-shrimp-bawan"},
        {"name": "東香台菜海味料理", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/tainan-region/tainan/restaurant/dong-shang-taiwanese-seafood"},
        {"name": "蓮霧腳羊肉湯", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/tainan-region/tainan/restaurant/lien-wu-chiao-lamb-soup"},
        {"name": "Lumière", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/tainan-region/tainan/restaurant/lumiere-1245897"},
        {"name": "咩灣裡羊肉店", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/tainan-region/tainan/restaurant/baa-wanli-goat"},
    ],
    "高雄": [
        {"name": "小燉食室", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/kaohsiung-region/kaohsiung/restaurant/simmer-house"},
        {"name": "米院子油飯", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/kaohsiung-region/kaohsiung/restaurant/mi-yuan-tzu-steamed-glutinous-rice"},
        {"name": "春蘭割包", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/kaohsiung-region/kaohsiung/restaurant/chun-lan-gua-bao"},
        {"name": "泰元", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/kaohsiung-region/kaohsiung/restaurant/thai-yuan"},
        {"name": "牛老大涮牛肉 (自強二路)", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/kaohsiung-region/kaohsiung/restaurant/beef-chief-zihciang-2nd-road"},
        {"name": "菜粽李", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/kaohsiung-region/kaohsiung/restaurant/caizong-li"},
        {"name": "前金肉燥飯", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/kaohsiung-region/kaohsiung/restaurant/cianjin-brasied-pork-rice"},
        {"name": "昭明海產家庭料理", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/kaohsiung-region/kaohsiung/restaurant/chao-ming"},
        {"name": "永筵小館", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/kaohsiung-region/kaohsiung/restaurant/yung-yen"},
        {"name": "侯記鴨肉飯", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/kaohsiung-region/kaohsiung/restaurant/hou-chi-duck-rice"},
        {"name": "白玉樓", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/kaohsiung-region/kaohsiung/restaurant/pale-jade-pavilion"},
        {"name": "北港蔡三代筒仔米糕 (鹽埕)", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/kaohsiung-region/kaohsiung/restaurant/bei-gang-tsai-rice-tube-yancheng"},
        {"name": "良佳豬腳", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/kaohsiung-region/kaohsiung/restaurant/liang-chia-pig-knuckle"},
        {"name": "貳哥食堂", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/kaohsiung-region/kaohsiung/restaurant/erge-shih-tang"},
        {"name": "賣塩順", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/kaohsiung-region/kaohsiung/restaurant/mai-yen-shun"},
        {"name": "正宗鴨肉飯", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/kaohsiung-region/kaohsiung/restaurant/cheng-tsung-duck-rice"},
        {"name": "弘記肉燥飯舖", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/kaohsiung-region/kaohsiung/restaurant/hung-chi-rice-shop"},
        {"name": "楊寶寶蒸餃 (朝明路)", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/kaohsiung-region/kaohsiung/restaurant/yang-bao-bao-nanzih"},
        {"name": "廖記米糕", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/kaohsiung-region/kaohsiung/restaurant/liao-chi-migao"},
        {"name": "橋仔頭黃家肉燥飯 (橋頭)", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/kaohsiung-region/kaohsiung/restaurant/ciao-zai-tou-huang-s-braised-pork-rice-ciaotou"},
        {"name": "舊市羊肉 (岡山)", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/kaohsiung-region/kaohsiung/restaurant/joes-gangshan"},
        {"name": "湖東牛肉館", "type": "", "desc": "米其林必比登推介", "url": "https://guide.michelin.com/tw/zh_TW/kaohsiung-region/kaohsiung/restaurant/hu-dong-beef"},
    ],
}  # fallback

# ─── 城市特色食物（觀光客/外地人必吃）──────────────────────
_CITY_SPECIALTIES: dict = _load_json("city_specialties.json", {})
if not _CITY_SPECIALTIES:
    _CITY_SPECIALTIES = {
    "台北": [
        {"name": "臭豆腐", "desc": "士林夜市必吃，外酥內嫩配泡菜，越臭越香", "key": "台北 臭豆腐", "s": ""},
        {"name": "蚵仔煎", "desc": "飽滿蚵仔加米漿皮，夜市人氣王", "key": "台北 蚵仔煎", "s": ""},
        {"name": "刈包", "desc": "台灣虎咬豬，軟饅頭夾控肉酸菜花生", "key": "台北 刈包", "s": ""},
        {"name": "豬血糕", "desc": "士林夜市限定體驗，花生粉香菜大爆發", "key": "台北 豬血糕", "s": ""},
        {"name": "滷肉飯", "desc": "台北靈魂飯，油蔥香氣一口就上癮", "key": "台北 滷肉飯", "s": ""},
        {"name": "公館粉圓", "desc": "師大夜市周邊古早味粉圓冰，消暑必吃", "key": "台北 粉圓冰", "s": "hot"},
        {"name": "紅豆餅", "desc": "街頭現烤車輪餅，紅豆奶油口味各有擁護者", "key": "台北 車輪餅", "s": ""},
    ],
    "新北": [
        {"name": "三峽金牛角", "desc": "三峽老街必買，酥脆牛角麵包香甜不膩", "key": "三峽 金牛角", "s": ""},
        {"name": "深坑臭豆腐", "desc": "深坑老街名物，炸臭豆腐外酥內嫩全台聞名", "key": "深坑 臭豆腐", "s": ""},
        {"name": "淡水魚丸", "desc": "淡水老街必吃，魚漿包肉餡Q彈有嚼勁", "key": "淡水 魚丸", "s": ""},
        {"name": "淡水阿給", "desc": "油豆腐填冬粉加魚漿封口，淡水獨有名點", "key": "淡水 阿給", "s": ""},
        {"name": "九份芋圓", "desc": "九份老街海景配芋圓，暖熱冰涼都好吃", "key": "九份 芋圓", "s": ""},
        {"name": "鶯歌陶瓷碗公冰", "desc": "鶯歌陶博館周邊，陶瓷碗盛裝復古剉冰", "key": "鶯歌 冰", "s": "hot"},
    ],
    "基隆": [
        {"name": "鼎邊銼", "desc": "基隆廟口第一名，米漿刮鍋邊煮成的獨特小吃", "key": "基隆 鼎邊銼", "s": ""},
        {"name": "天婦羅", "desc": "基隆港邊魚漿炸物，沾甜辣醬超對味", "key": "基隆 天婦羅", "s": ""},
        {"name": "泡泡冰", "desc": "基隆獨有冰品，轉出泡泡造型，花生芋頭口味人氣高", "key": "基隆 泡泡冰", "s": "hot"},
        {"name": "三明治（基隆式）", "desc": "基隆夜市古早味三明治，蛋沙拉夾吐司超厚實", "key": "基隆 三明治", "s": ""},
        {"name": "豆簽羹", "desc": "廟口名物，豆粉做成豆簽配海鮮羹，古早又暖胃", "key": "基隆 豆簽羹", "s": ""},
        {"name": "營養三明治", "desc": "炸麵包夾蛋沙拉番茄，基隆人的早餐記憶", "key": "基隆 營養三明治", "s": ""},
    ],
    "桃園": [
        {"name": "大溪豆干", "desc": "大溪老街百年豆干，滷得入味帶勁香", "key": "大溪 豆干", "s": ""},
        {"name": "客家粄條", "desc": "龍潭、楊梅客家粄條，米香軟Q配豬油蔥", "key": "桃園 客家粄條", "s": ""},
        {"name": "復興山豬肉", "desc": "復興鄉原住民風味，山豬肉香辣下飯", "key": "復興 山豬肉 原住民", "s": ""},
        {"name": "石門活魚", "desc": "石門水庫旁現撈活魚，三吃吃法各有風味", "key": "石門水庫 活魚", "s": ""},
        {"name": "龍潭花生糖", "desc": "客家傳統花生糖，香甜不黏牙伴手禮首選", "key": "龍潭 花生糖", "s": ""},
        {"name": "蘆竹米干", "desc": "緬甸風味米干，桃園東南亞移民帶來的滋味", "key": "桃園 米干", "s": ""},
    ],
    "新竹": [
        {"name": "貢丸湯", "desc": "新竹貢丸Q彈有嚼勁，湯底清甜暖胃", "key": "新竹 貢丸湯", "s": ""},
        {"name": "新竹米粉", "desc": "新竹九降風吹出細如絲的米粉，炒或煮都香", "key": "新竹 米粉", "s": ""},
        {"name": "柿餅", "desc": "新竹九降風吹出的古早味，秋冬最甜最香", "key": "新竹 柿餅", "s": "cold"},
        {"name": "潤餅", "desc": "新竹傳統潤餅捲，花生糖粉＋蛋＋豆芽料多實在", "key": "新竹 潤餅", "s": ""},
        {"name": "城隍廟廟口小吃", "desc": "新竹城隍廟周邊肉燥飯、湯圓、貢丸一條街", "key": "新竹城隍廟 小吃", "s": ""},
        {"name": "仙草雞", "desc": "關西仙草產地直送，仙草燉雞清潤去火", "key": "關西 仙草雞", "s": ""},
    ],
    "苗栗": [
        {"name": "客家湯圓", "desc": "苗栗客家湯圓包豬肉，油蔥拌炒香氣滿滿", "key": "苗栗 客家湯圓", "s": "cold"},
        {"name": "梅干扣肉", "desc": "客家媽媽的味道，梅干菜吸飽豬油滷汁超下飯", "key": "苗栗 梅干扣肉", "s": ""},
        {"name": "薑絲大腸", "desc": "客家名菜，嫩大腸配嫩薑絲酸辣開胃", "key": "苗栗 薑絲大腸", "s": ""},
        {"name": "銅鑼杭菊茶", "desc": "銅鑼杭菊產地，秋冬菊花茶清香退火", "key": "銅鑼 杭菊茶", "s": "cold"},
        {"name": "大湖草莓", "desc": "大湖草莓園採摘體驗，冬季限定最甜", "key": "大湖 草莓", "s": "cold"},
        {"name": "南庄桂花釀", "desc": "南庄老街桂花系列飲品甜點，香氣迷人", "key": "南庄 桂花", "s": ""},
    ],
    "台中": [
        {"name": "太陽餅", "desc": "台中伴手禮一號，酥皮麥芽糖內餡香甜", "key": "台中 太陽餅", "s": ""},
        {"name": "珍珠奶茶（發源地）", "desc": "珍珠奶茶在台中春水堂發明，原汁原味", "key": "台中 春水堂 珍珠奶茶", "s": ""},
        {"name": "逢甲夜市鹹酥雞", "desc": "逢甲夜市必逛，現炸鹹酥雞配九層塔", "key": "逢甲夜市 鹹酥雞", "s": ""},
        {"name": "草莓大福", "desc": "新社草莓季必吃，新鮮草莓包白玉麻糬", "key": "台中 草莓大福", "s": "cold"},
        {"name": "肉蛋吐司", "desc": "台中早餐象徵，鐵板蛋＋貢丸＋吐司超滿足", "key": "台中 肉蛋吐司", "s": ""},
        {"name": "宮原眼科冰淇淋", "desc": "台中網紅景點，古典建築配義式冰淇淋塔", "key": "台中 宮原眼科 冰淇淋", "s": "hot"},
        {"name": "三時茶房鳳梨酥", "desc": "宮原集團出品，台中土鳳梨酥送禮超體面", "key": "台中 鳳梨酥", "s": ""},
    ],
    "彰化": [
        {"name": "彰化肉圓", "desc": "彰化名物，蒸熟軟Q外皮包筍丁豬肉，醬汁甘甜", "key": "彰化 肉圓", "s": ""},
        {"name": "爌肉飯", "desc": "彰化老字號，整塊控肉滷到入骨超下飯", "key": "彰化 爌肉飯", "s": ""},
        {"name": "貓鼠麵", "desc": "彰化百年老店，意麵配豬雜湯獨特古早味", "key": "彰化 貓鼠麵", "s": ""},
        {"name": "王功蚵仔", "desc": "王功漁港現撈蚵仔，鮮甜肥美直接吃最過癮", "key": "王功 蚵仔 海鮮", "s": ""},
        {"name": "溪湖羊肉", "desc": "溪湖羊肉爐聞名全台，冬季進補必來", "key": "溪湖 羊肉爐", "s": "cold"},
        {"name": "鹿港蚵仔煎", "desc": "鹿港老街必吃，蚵仔新鮮肥大，米漿外皮香脆", "key": "鹿港 蚵仔煎", "s": ""},
        {"name": "鹿港鳳眼糕", "desc": "鹿港傳統糕點，米粉製成細緻香甜", "key": "鹿港 鳳眼糕", "s": ""},
    ],
    "南投": [
        {"name": "竹筒飯", "desc": "信義鄉原住民竹筒飯，現烤竹香滲入米飯", "key": "南投 竹筒飯 原住民", "s": ""},
        {"name": "紹興酒蛋", "desc": "埔里紹興酒廠名物，酒香濃郁滷蛋入味", "key": "埔里 紹興酒蛋", "s": ""},
        {"name": "日月潭紅茶", "desc": "日月潭阿薩姆紅茶，茶色艷紅滋味甘醇", "key": "日月潭 紅茶", "s": ""},
        {"name": "埔里米粉", "desc": "埔里盆地好水製成米粉，煮炒皆宜", "key": "埔里 米粉", "s": ""},
        {"name": "廬山溫泉烤玉米", "desc": "廬山路邊現烤玉米，甜脆噴香", "key": "南投 烤玉米", "s": ""},
        {"name": "水里蛇窯陶藝餐", "desc": "水里特色體驗，陶甕料理視覺味覺雙享受", "key": "水里 陶藝 料理", "s": ""},
    ],
    "雲林": [
        {"name": "斗六意麵", "desc": "雲林特色麵食，鹼水意麵配肉燥湯頭鮮甜", "key": "斗六 意麵", "s": ""},
        {"name": "虎尾毛巾蛋糕", "desc": "虎尾毛巾工廠轉型，毛巾造型蛋糕超可愛", "key": "虎尾 毛巾蛋糕", "s": ""},
        {"name": "北港花生", "desc": "北港農產直銷花生糖、花生酥，香氣四溢", "key": "北港 花生糖", "s": ""},
        {"name": "口湖烏魚子", "desc": "口湖漁港鮮製烏魚子，送禮自用兩相宜", "key": "口湖 烏魚子", "s": "cold"},
        {"name": "古坑咖啡", "desc": "古坑台灣咖啡產地，現烤咖啡豆香氣迷人", "key": "古坑 台灣咖啡", "s": ""},
        {"name": "西螺醬油", "desc": "西螺百年醬油文化，原釀醬油拌飯超香", "key": "西螺 醬油 小吃", "s": ""},
    ],
    "嘉義": [
        {"name": "火雞肉飯", "desc": "嘉義市標誌美食，火雞腿絲淋滷汁超香", "key": "嘉義 火雞肉飯", "s": ""},
        {"name": "方塊酥", "desc": "嘉義特色零食，酥脆鹹甜一口接一口停不下來", "key": "嘉義 方塊酥", "s": ""},
        {"name": "阿里山愛玉", "desc": "阿里山天然愛玉自己搓，配蜂蜜檸檬超純淨", "key": "阿里山 愛玉", "s": "hot"},
        {"name": "奮起湖便當", "desc": "阿里山鐵路便當，竹製餐盒古早香名聞全台", "key": "奮起湖便當", "s": ""},
        {"name": "東石蚵仔", "desc": "東石漁港現撈蚵仔，蚵仔麵線蚵仔煎都鮮", "key": "東石 蚵仔", "s": ""},
        {"name": "嘉義布丁", "desc": "嘉義特色古早味布丁，雞蛋奶香焦糖濃郁", "key": "嘉義 布丁", "s": ""},
    ],
    "台南": [
        {"name": "紅磚布丁", "desc": "台南排隊名物，古早味雞蛋布丁冷吃最香", "key": "台南 紅磚布丁", "s": ""},
        {"name": "虱目魚粥", "desc": "台南早餐靈魂，鮮甜虱目魚配清粥無腥味", "key": "台南 虱目魚粥", "s": ""},
        {"name": "擔仔麵", "desc": "台南百年老味道，度小月湯頭鮮甜不膩", "key": "台南 擔仔麵", "s": ""},
        {"name": "鱔魚意麵", "desc": "台南獨有大火炒法，鑊氣十足滑嫩入味", "key": "台南 鱔魚意麵", "s": ""},
        {"name": "碗粿", "desc": "軟Q米食加肉燥蒸熟，沾蒜蓉醬超下飯", "key": "台南 碗粿", "s": ""},
        {"name": "土魠魚羹", "desc": "台灣鯧魚炸酥後加羹，鮮甜濃郁台南招牌", "key": "台南 土魠魚羹", "s": ""},
        {"name": "粉粿", "desc": "古早粉粿加黑糖水，夏天消暑必吃", "key": "台南 粉粿", "s": "hot"},
        {"name": "棺材板", "desc": "延平街名物，厚吐司挖空填濃郁白醬海鮮", "key": "台南 棺材板", "s": ""},
    ],
    "高雄": [
        {"name": "木瓜牛奶", "desc": "高雄鹽埕傳統木瓜牛奶，甜而不膩消暑聖品", "key": "高雄 木瓜牛奶", "s": ""},
        {"name": "旗魚黑輪", "desc": "旗津海邊必吃，現炸旗魚黑輪卡卡脆", "key": "高雄 旗魚黑輪", "s": ""},
        {"name": "鹽埕肉圓", "desc": "高雄老城區古早味，外皮Q彈肉餡飽滿", "key": "高雄 鹽埕 肉圓", "s": ""},
        {"name": "岡山羊肉爐", "desc": "岡山三寶之一，羊肉爐配蒜苗冬季必補", "key": "岡山 羊肉爐", "s": "cold"},
        {"name": "美濃板條", "desc": "美濃客家粄條，豬油蔥拌炒米香撲鼻", "key": "美濃 板條 粄條", "s": ""},
        {"name": "旗山香蕉", "desc": "旗山香蕉之鄉，香蕉冰淇淋香蕉蛋糕超值得買", "key": "旗山 香蕉 冰淇淋", "s": ""},
        {"name": "六合夜市海鮮", "desc": "高雄夜市全覽，生猛海鮮炒飯烤肉一條街", "key": "高雄 六合夜市 海鮮", "s": ""},
    ],
    "屏東": [
        {"name": "潮州燒冷冰", "desc": "屏東潮州名物，熱湯澆剉冰獨特吃法超特別", "key": "屏東 潮州 燒冷冰", "s": "hot"},
        {"name": "萬巒豬腳", "desc": "萬巒豬腳全台聞名，皮Q肉嫩滷汁入骨", "key": "萬巒 豬腳", "s": ""},
        {"name": "東港黑鮪魚", "desc": "東港黑鮪魚季（4-6月）生魚片最鮮最肥", "key": "東港 黑鮪魚", "s": "hot"},
        {"name": "屏東起司蛋糕", "desc": "屏東牧場直送鮮奶，起司蛋糕濃郁香滑", "key": "屏東 起司蛋糕", "s": ""},
        {"name": "恆春洋蔥", "desc": "恆春半島特產，洋蔥甜脆多汁，各式料理皆宜", "key": "恆春 洋蔥料理", "s": ""},
        {"name": "小琉球烤小卷", "desc": "小琉球海邊烤小卷，現烤鮮甜配蒜蓉醬", "key": "小琉球 烤小卷 海鮮", "s": ""},
    ],
    "宜蘭": [
        {"name": "鴨賞", "desc": "宜蘭三星特產，煙燻鴨肉切薄片超下酒", "key": "宜蘭 鴨賞", "s": ""},
        {"name": "牛舌餅", "desc": "宜蘭形狀像牛舌的甜餅，酥脆香甜伴手禮", "key": "宜蘭 牛舌餅", "s": ""},
        {"name": "糕渣", "desc": "外脆內燙的宜蘭名點，雞肉濃湯凝固炸酥", "key": "宜蘭 糕渣", "s": ""},
        {"name": "卜肉", "desc": "里肌裹地瓜粉油炸，外酥內嫩宜蘭獨有", "key": "宜蘭 卜肉", "s": ""},
        {"name": "三星蔥餅", "desc": "宜蘭三星蔥現烤蔥餅，香氣撲鼻超誘人", "key": "宜蘭 三星蔥餅", "s": ""},
        {"name": "羅東夜市小吃", "desc": "羅東夜市炭烤、肉羹、蒜味肉排，夜晚必訪", "key": "羅東夜市 小吃", "s": ""},
        {"name": "蘇澳冷泉蝦", "desc": "蘇澳天然冷泉養殖蝦，鮮甜清甜口感細嫩", "key": "蘇澳 冷泉蝦", "s": ""},
    ],
    "花蓮": [
        {"name": "麻糬", "desc": "花蓮必帶伴手禮，芝麻花生口味人氣最高", "key": "花蓮 麻糬", "s": ""},
        {"name": "奶油酥條", "desc": "花蓮特產，奶香濃厚酥脆不油膩", "key": "花蓮 奶油酥條", "s": ""},
        {"name": "原住民風味餐", "desc": "小米酒、烤山豬肉、吉拿富，體驗阿美族文化", "key": "花蓮 原住民料理", "s": ""},
        {"name": "東坡肉便當", "desc": "花蓮名產控肉便當，軟爛入味超下飯", "key": "花蓮 東坡肉便當", "s": ""},
        {"name": "芋頭冰淇淋", "desc": "花蓮芋頭細緻甜香，冰淇淋口感迷人", "key": "花蓮 芋頭冰淇淋", "s": "hot"},
        {"name": "公正包子", "desc": "花蓮老字號，大顆肉包皮薄餡多排隊必吃", "key": "花蓮 公正包子", "s": ""},
        {"name": "壽豐鮭魚料理", "desc": "壽豐鮭魚產地，生魚片握壽司鮮甜肥美", "key": "壽豐 鮭魚 生魚片", "s": ""},
    ],
    "台東": [
        {"name": "釋迦", "desc": "台東最出名水果，果肉甜如蜜，產季必吃", "key": "台東 釋迦", "s": ""},
        {"name": "黑糖麻糬", "desc": "池上黑糖麻糬，現做Q彈甜蜜蜜", "key": "台東 黑糖麻糬", "s": ""},
        {"name": "關山便當", "desc": "台東縱谷米飯超香，關山火車便當排隊名物", "key": "關山便當", "s": ""},
        {"name": "旗魚米苔目", "desc": "台東在地早餐，旗魚湯頭加Q彈米苔目", "key": "台東 米苔目", "s": ""},
        {"name": "卑南豬血湯", "desc": "台東特色早餐，豬血鮮嫩湯底清甜暖胃", "key": "台東 豬血湯", "s": ""},
        {"name": "都蘭薯餅", "desc": "都蘭部落風味薯餅，地瓜香甜嚼勁十足", "key": "台東 都蘭 薯餅", "s": ""},
        {"name": "成功旗魚飯糰", "desc": "成功漁港新鮮旗魚製成旗魚飯糰，海味十足", "key": "成功 旗魚飯糰", "s": ""},
    ],
    "澎湖": [
        {"name": "仙人掌冰", "desc": "澎湖夏季限定！天然仙人掌汁製成紫紅冰棒", "key": "澎湖 仙人掌冰", "s": "hot"},
        {"name": "現撈海鮮", "desc": "小管、龍蝦、九孔現撈直送，新鮮無比", "key": "澎湖 海鮮", "s": ""},
        {"name": "花生糖", "desc": "澎湖傳統花生糖，香甜不黏牙代代相傳", "key": "澎湖 花生糖", "s": ""},
        {"name": "黑糖糕", "desc": "澎湖名產Q彈黑糖麻糬口感，送禮首選", "key": "澎湖 黑糖糕", "s": ""},
        {"name": "丁香魚飯", "desc": "澎湖丁香魚炸酥配白飯，鮮鹹下飯超獨特", "key": "澎湖 丁香魚", "s": ""},
        {"name": "澎湖文蛤", "desc": "澎湖養殖文蛤肉厚鮮甜，蒸或煮都一絕", "key": "澎湖 文蛤 海鮮", "s": ""},
    ],
    "金門": [
        {"name": "貢糖", "desc": "金門必帶伴手禮，花生芝麻酥脆香甜", "key": "金門 貢糖", "s": ""},
        {"name": "高粱酒料理", "desc": "金門高粱酒入菜，醉雞醉蝦風味獨特", "key": "金門 高粱 料理", "s": ""},
        {"name": "金門麵線", "desc": "金門傳統曬麵線，湯頭鮮甜麵條細緻", "key": "金門 麵線", "s": ""},
        {"name": "蚵仔麵線", "desc": "金門蚵仔肥美配細麵線，鮮甜濃郁", "key": "金門 蚵仔麵線", "s": ""},
        {"name": "廣東粥", "desc": "金門早餐文化，食材豐富粥底綿密", "key": "金門 廣東粥", "s": ""},
    ],
    "連江": [
        {"name": "老酒麵線", "desc": "馬祖紅糟老酒入麵線，酒香濃郁暖胃", "key": "馬祖 老酒麵線", "s": "cold"},
        {"name": "繼光餅", "desc": "馬祖傳統硬餅，夾蛋夾肉都好吃", "key": "馬祖 繼光餅", "s": ""},
        {"name": "淡菜", "desc": "馬祖海域現撈淡菜，肉質肥美鮮甜", "key": "馬祖 淡菜 海鮮", "s": ""},
        {"name": "魚麵", "desc": "馬祖傳統魚漿製成的魚麵，Q彈有嚼勁", "key": "馬祖 魚麵", "s": ""},
        {"name": "芙蓉酥", "desc": "馬祖傳統糕點，鬆軟香甜帶花香", "key": "馬祖 芙蓉酥", "s": ""},
    ],
}  # fallback
